services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
#    healthcheck:
#      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/health" ]
#      interval: 10s
#      timeout: 3s
#      retries: 10

  node-package-install:
    image: oven/bun:1-alpine
    working_dir: /var/www/frontend
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    command: "bun install"

  node:
    image: oven/bun:1-alpine
    working_dir: /var/www/frontend
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    depends_on:
#      app:
#        condition: service_healthy
      node-package-install:
        condition: service_completed_successfully
    command: "bun run dev --host"