
FROM oven/bun:1-alpine AS frontend
COPY frontend /app
COPY .env.production /.env
WORKDIR /app
RUN bun install
RUN bun run build

FROM golang:1.26.1-alpine3.23 AS backend
COPY . /app
WORKDIR /app
COPY --from=frontend /cmd/snake/static ./cmd/snake/static
RUN go mod download -x
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o main ./cmd/snake/main.go

FROM scratch
COPY --from=backend /app/main main
CMD ["/main"]